// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdrP6RN_7FeolgEsC7U7QP2dhKEEMMiGE',
    appId: '1:121751141991:web:caf3122eeeb9e292515ec2',
    messagingSenderId: '121751141991',
    projectId: 'fibbly-82d0d',
    authDomain: 'fibbly-82d0d.firebaseapp.com',
    storageBucket: 'fibbly-82d0d.firebasestorage.app',
    measurementId: 'G-D4W7JB4KYT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRFLmK2m--VfpKAx76mZqVuG4n_VJS6no',
    appId: '1:121751141991:android:074b84622d397f5e515ec2',
    messagingSenderId: '121751141991',
    projectId: 'fibbly-82d0d',
    storageBucket: 'fibbly-82d0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvmpDCrZ9rC8G3y2YDRhXouxsWQq2TamI',
    appId: '1:121751141991:ios:5c70f1fa43a610d5515ec2',
    messagingSenderId: '121751141991',
    projectId: 'fibbly-82d0d',
    storageBucket: 'fibbly-82d0d.firebasestorage.app',
    iosBundleId: 'com.example.fibbly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvmpDCrZ9rC8G3y2YDRhXouxsWQq2TamI',
    appId: '1:121751141991:ios:5c70f1fa43a610d5515ec2',
    messagingSenderId: '121751141991',
    projectId: 'fibbly-82d0d',
    storageBucket: 'fibbly-82d0d.firebasestorage.app',
    iosBundleId: 'com.example.fibbly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdrP6RN_7FeolgEsC7U7QP2dhKEEMMiGE',
    appId: '1:121751141991:web:cb756ca9812874f5515ec2',
    messagingSenderId: '121751141991',
    projectId: 'fibbly-82d0d',
    authDomain: 'fibbly-82d0d.firebaseapp.com',
    storageBucket: 'fibbly-82d0d.firebasestorage.app',
    measurementId: 'G-ZFES9YGRHF',
  );
}